name: wails3 multiple platforms package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
#  build:
#    strategy:
#      fail-fast: false
#      matrix:
#        build: [
##          { name: wechat-dual-desktop-windows, uns-on: windows-latest, archs: 'arm64, amd64' },
#          { name: wechat-dual-desktop-mac, runs-on: macos-latest, archs: 'universal, arm64, amd64'  },
#        ]
#    runs-on: ${{ matrix.build.runs-on }}
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          submodules: recursive
#      - uses: toquery/wails3-build-action@v3-alpha.14
#        with:
#          go-archs: ${{ matrix.build.archs }}
#          pnpm-build: true
#          build-obfuscate: false
  test-action:
    runs-on: macos-latest # 或 ubuntu-latest、windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test my action
        uses: ./ # 直接引用当前仓库根目录下的 action.yml
        with:
          go-archs: 'arm64, amd64'
          pnpm-build: true
          build-obfuscate: false
